-- RETORNA TODOS OS CLIENTES 
SELECT * FROM Clientes

-- RETORNA TODOS OS CLIENTES QUE CONTEM A NO NOME
SELECT * FROM Clientes WHERE Nome LIKE '%A%'


-- RETORNA CLIENTES POR ID
SELECT * FROM Clientes WHERE id = {id}